version: '3.8'
services:
  react-app:
    image: red-llama-jc-web:latest
    build: .
    environment:
      VIRTUAL_HOST: redllamajc.com
      LETSENCRYPT_HOST: redllamajc.com
      LETSENCRYPT_EMAIL: kevin.silva.095@gmail.com
    expose:
      - "80"

    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
